# Generated by Django 5.0.4 on 2024-11-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('denied', 'Denied'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
