# Generated by Django 5.0.4 on 2024-10-31 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0004_alter_booking_booking_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('residential', 'Residential Cleaning'), ('commercial', 'Commercial Cleaning'), ('deep_cleaning', 'Deep Cleaning'), ('move_in_out', 'Move-in/Move-out Cleaning'), ('carpet_cleaning', 'Carpet Cleaning'), ('upholstery_cleaning', 'Upholstery Cleaning'), ('window_cleaning', 'Window Cleaning'), ('eco_friendly', 'Eco-friendly Green Cleaning')], max_length=50)),
                ('rating', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('booking_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
