# Generated by Django 5.0.4 on 2024-11-02 07:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0005_servicerating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicerating',
            unique_together={('user', 'service_name', 'month')},
        ),
        migrations.RemoveField(
            model_name='servicerating',
            name='booking_id',
        ),
    ]
