# Generated by Django 5.0.4 on 2024-11-07 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0007_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
