# Generated by Django 5.0.4 on 2024-11-10 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0008_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.date(2024, 11, 10)),
            preserve_default=False,
        ),
    ]
