# Generated by Django 5.0.4 on 2024-11-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0009_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cleaning_service',
            field=models.CharField(choices=[('residential', 'Residential Cleaning'), ('commercial', 'Commercial Cleaning'), ('deep-cleaning', 'Deep Cleaning'), ('move-in-out', 'Move-in/Move-out Cleaning'), ('carpet-cleaning', 'Carpet Cleaning'), ('upholstery-cleaning', 'Upholstery Cleaning'), ('window-cleaning', 'Window Cleaning'), ('eco-friendly', 'Eco-friendly Green Cleaning'), ('anti-bacterial-mist', 'Anti-Bacterial Mist Treatment'), ('car-interior-detailing', 'Car Interior Detailing'), ('deep-dry-cleaning', 'Deep Dry Cleaning'), ('deep-home-cleaning', 'Deep Home Cleaning'), ('deep-upholstery-shampooing', 'Deep Upholstery Shampooing'), ('steam-sterilization', 'Superior Steam Sterilization')], max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='service_name',
            field=models.CharField(choices=[('residential', 'Residential Cleaning'), ('commercial', 'Commercial Cleaning'), ('deep-cleaning', 'Deep Cleaning'), ('move-in-out', 'Move-in/Move-out Cleaning'), ('carpet-cleaning', 'Carpet Cleaning'), ('upholstery-cleaning', 'Upholstery Cleaning'), ('window-cleaning', 'Window Cleaning'), ('eco-friendly', 'Eco-friendly Green Cleaning'), ('anti-bacterial-mist', 'Anti-Bacterial Mist Treatment'), ('car-interior-detailing', 'Car Interior Detailing'), ('deep-dry-cleaning', 'Deep Dry Cleaning'), ('deep-home-cleaning', 'Deep Home Cleaning'), ('deep-upholstery-shampooing', 'Deep Upholstery Shampooing'), ('steam-sterilization', 'Superior Steam Sterilization')], max_length=50),
        ),
    ]
